# Generated by Django 5.2 on 2025-04-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('South Indian', 'South Indian'), ('North Indian', 'North Indian'), ('Chinese', 'Chinese'), ('Biryani', 'Biryani')], default='Main Course', max_length=50),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='dish_images/'),
        ),
    ]
