# Generated by Django 5.2 on 2025-04-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_category_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=20),
        ),
    ]
