# Generated by Django 5.2 on 2025-04-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='type',
            new_name='dish_type',
        ),
    ]
