# Generated by Django 5.2 on 2025-04-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='old_entry@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Old_Enty', max_length=100),
            preserve_default=False,
        ),
    ]
